buildVariable: false
familyName: Noto Sans Old North Arabian
googleFonts: true
includeSubsets:
- from: Noto Sans
  name: GF_Latin_Core
recipeProvider: noto
sources:
- NotoSansOldNorthArabian.designspace
